name: Daily Deploy
on:
  schedule:
    - cron: "17 0 * * *"
  workflow_dispatch:
jobs:
  deploy-cloudflare-pages:
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST "${CF_DEPLOY_HOOK}"
        env:
          CF_DEPLOY_HOOK: ${{ secrets.CF_DEPLOY_HOOK }}
